sudo: false
language: ruby

before_install:
  - gem update --system

matrix:
  include:
    - rvm: 2.5.0
    - rvm: 2.4.2
    - rvm: 2.3.5
    - rvm: 2.2.8
    - rvm: 2.1.10

notfications:
  email: false
